config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: 'web' do
    root to: 'welcome#index'

    namespace :admin do
      resources :tasks, only: :index
    end

    resources :tasks do
      scope module: :tasks do
        Task.aasm.events.each do |state|
          next if state.options[:initial]
          resource state.name, controller: state.name, only: :create
        end
      end
    end

    get    '/login', to: 'sessions#new'
    post   '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  default_scope { order(:created_at) }

  include AASM

  belongs_to :user

  validates :name, presence: true, length: { in: 5..50 }
  validates :state, presence: true

  aasm column: :state do
    state :new, initial: true
    state :started, :finished

    event :start do
      transitions from: :new, to: :started
    end

    event :finish do
      transitions from: :started, to: :finished
    end
  end

  delegate :user_name, to: :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  enum role: %I[admin user]

  has_many :tasks, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    length: { in: 6..120 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { in: 6..30 }
  validates :role, presence: true

  before_save { email&.downcase! }

  has_secure_password

  def user_name
    email
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/web/admin/tasks_controller.rb
# frozen_string_literal: true

class Web::Admin::TasksController < Web::TasksController
  before_action :check_admin

  def index
    @presenter = Web::Tasks::AdminTasksPresenter.new(current_user)
  end
end

app/controllers/web/application_controller.rb
# frozen_string_literal: true

class Web::ApplicationController < ApplicationController
  protect_from_forgery with: :exception
  before_action :check_user_logged_in
  include SessionsHelper

  private

  def check_user_logged_in
    return if logged_in?

    flash[:danger] = 'Please log in.'
    redirect_to login_path
  end

  def check_admin
    return if current_user.admin?

    flash[:danger] = 'You have not permissions to do that!'
    redirect_to user_cab_path
  end
end

app/controllers/web/sessions_controller.rb
# frozen_string_literal: true

class Web::SessionsController < Web::ApplicationController
  skip_before_action :check_user_logged_in, only: %I[new create]

  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user&.authenticate(params[:session][:password])
      log_in user
      return
    end

    flash.now[:danger] = 'Invalid email/password combination'
    render 'new'
  end

  def destroy
    log_out
    redirect_to login_path
  end
end

app/controllers/web/tasks/application_controller.rb
# frozen_string_literal: true

class Web::Tasks::ApplicationController < Web::TasksController
  before_action :presenter

  private

  def presenter
    @presenter ||= params[:presenter].constantize.new(current_user)
  end

  def task
    # for nested resource id param changes to task_id param
    @task ||= Task.find_by(id: params.fetch(:task_id, nil))
  end
end

app/controllers/web/tasks/finish_controller.rb
# frozen_string_literal: true

class Web::Tasks::FinishController < Web::Tasks::ApplicationController
  def create
    task.finish!
  end
end

app/controllers/web/tasks/start_controller.rb
# frozen_string_literal: true

class Web::Tasks::StartController < Web::Tasks::ApplicationController
  def create
    task.start!
  end
end

app/controllers/web/tasks_controller.rb
# frozen_string_literal: true

class Web::TasksController < Web::ApplicationController
  before_action :task, only: %I[show edit update destroy]
  before_action :check_task_owner, only: %I[edit destroy]

  def index
    @presenter = Web::Tasks::UserTasksPresenter.new(current_user)
  end

  def show; end

  def edit; end

  def new
    @task = current_user.tasks.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      flash[:notice] = 'Task created!'
      redirect_to @task
    else
      render 'new'
    end
  end

  def update
    if task.update(task_params)
      flash[:notice] = 'Task updated'
      redirect_to task
    else
      render 'edit'
    end
  end

  def destroy
    task.destroy!
    flash[:notice] = 'Task deleted'
    redirect_to user_cab_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :state, :user_id, :image,
                                 :image_cache)
  end

  def task
    @task ||= Task.find_by(id: params.fetch(:id, nil))
  end

  def check_task_owner
    return if task.user == current_user || current_user.admin?

    flash[:danger] = 'You have not permissions to do that!'
    redirect_to user_cab_path
  end
end

app/controllers/web/welcome_controller.rb
# frozen_string_literal: true

# Controller for main page
class Web::WelcomeController < Web::ApplicationController
  def index
    @presenter = Web::Tasks::BaseTasksPresenter.new(current_user)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_alert_class(flash_type)
    "alert-#{flash_type.to_s == 'notice' ? 'success' : 'danger'}"
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
    flash[:notice] = 'You logged in successfully'
    redirect_to user_cab_path
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    return unless session[:user_id]

    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def user_cab_path
    current_user.admin? ? admin_tasks_path : tasks_path
  end
end

app/views/layouts/_header.html.slim
nav.navbar.navbar-default.navbar-fixed-top role="navigation"
  .container-fluid
    .navbar-header
      button type="button" class="navbar-toggle" data-toggle="collapse"
             data-target="#bs-example-navbar-collapse-1"
      = link_to 'Task Manager', root_path, class: "navbar-brand", id: "logo"
    collapse.navbar-collapse id="bs-example-navbar-collapse-1"
      ul.nav.navbar-nav
        li = link_to 'Home', root_path
        - if logged_in?
          li = link_to 'My cab', user_cab_path
          li = link_to 'Log out', logout_path, method: :delete
        - else
          li = link_to 'Log in', login_path

app/views/layouts/_messages.html.slim
- flash.each do |flash_type, message|
  .alert role="alert" class="#{flash_alert_class(flash_type)}"
    button.close type="button" data-dismiss="alert" aria-hidden="true"
      |&times;
    = content_tag :div, message, id: "flash_#{flash_type}"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      TaskManager
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'layouts/header'
    .container
      = render 'layouts/messages'
      = yield

app/views/web/tasks/_form.html.slim
= simple_form_for @task do |f|
  = f.input :name
  = f.input :description
  - if current_user.admin?
    = f.association :user, label_method: :email, value_method: :id
  - else
    = f.input :user_id, as: :hidden
  = image_tag @task.image.thumb.url if @task.image?
  = f.input :image
  = f.hidden_field :image_cache
  = f.submit

app/views/web/tasks/_task.html.slim
tr id="task_id_#{task.id}"
  td = link_to task.id, task_path(task)
  td = l(task.created_at, format: :short)
  td = task.name
  td = task.state
  - presenter.extra_fields.each do |field|
    td = presenter.show_field(task, field)
  - if presenter.show_links?
    td
      - presenter.state_refs(task).each do |ref|
        = link_to ref[:name], ref[:url], ref[:options]
    td = link_to 'edit', edit_task_path(task)
    td = link_to 'delete', task_path(task), method: :delete,
                 data: { confirm: 'Are you shure?' }

app/views/web/tasks/edit.html.slim
h2 Task Edit Page
= render 'form'

app/views/web/tasks/index.html.slim
h2 User tasks
table.table
  tbody
    = render partial: 'task',
             collection: @presenter.task_list,
             locals: { presenter: @presenter }
.row
  .col
    = link_to 'Create new', new_task_path

app/views/web/tasks/new.html.slim
h2 Create New Task
= render 'form'

app/views/web/tasks/show.html.slim
h2 Task Details
.form-group
  = label @task, :name
  = text_field @task, :name,
                      value: @task.name,
                      class: 'form-control',
                      disabled: true

.form-group
  = label @task, :description
  = text_field @task, :description,
                      value: @task.description,
                      class: 'form-control',
                      disabled: true

.form-group
  = label @task, :user
  = text_field @task, :user,
                      value: @task.user_name,
                      class: 'form-control',
                      disabled: true

.form-group
  = label @task, :state
  = text_field @task, :state,
                      value: @task.state,
                      class: 'form-control',
                      disabled: true
.form-group
  = link_to image_tag(@task.image.thumb.url, alt: 'Image') if @task.image?

app/views/web/welcome/index.html.slim
h2 Main page
table.table
  tbody
    = render partial: 'web/tasks/task',
             collection: @presenter.task_list,
             locals: { presenter: @presenter }